# -*- coding: utf-8 -*-
"""Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-UOvjHCfF2N_EmZ6jYcK5SW00w3p3aj
"""

import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold
from sklearn.linear_model import LinearRegression

df = pd.read_csv('QualityMsrMDS_2015.csv')

df.dropna(thresh=len(df.columns)*0.8, inplace=True)
df.dropna(axis=1, thresh=len(df)*0.75, inplace=True)

df.drop(['q1_quarter','q2_quarter','q3_quarter','filedate'], axis=1, inplace=True)

df.dropna(inplace=True)

df.info()

bins = [0,25,50,75,100,101]
df['measure_score_3qtr_avg'] = pd.cut(df.measure_score_3qtr_avg, bins=bins).cat.codes

df["stay_type"] = df["stay_type"].astype('category').cat.codes

df.measure_score_3qtr_avg.value_counts()

df["five_star_msr"] = df["five_star_msr"].astype('category').cat.codes

y = df['five_star_msr']
X = df[['measure_score_3qtr_avg','stay_type','msr_cd']]

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

grid = {'max_depth' : [3,5,7], 'min_samples_leaf' : [0.02,0.03]}

clf = GridSearchCV(DecisionTreeClassifier(), param_grid= grid, cv=5,n_jobs=-1)
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

clf.score(X_test,y_test)

clf.best_params_

best = clf.best_estimator_

plt.figure(figsize=(20,10))
plot_tree(best, feature_names=X.columns)
plt.show()